---
os: linux
dist: xenial

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

services:
  - docker

script:
  - sbt ++$TRAVIS_SCALA_VERSION compile test:compile it:compile
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION it:test
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION coverageOff assembly
  - "${TRAVIS_BUILD_DIR}/travis/docker-build.sh"

scala:
  - 2.13.2

jdk:
  - openjdk8
  - openjdk11

after_success:
  - bash <(curl -s https://codecov.io/bash)
